const LOGGED_IN_REQUEST = "LOGGED_IN_REQUEST"
const LOGGED_IN_SUCCESSFUL = "LOGGED_IN_SUCCESSFUL"
const LOGGED_IN_FAILED = "LOGGED_IN_FAILED"
const LOGGED_OUT_REQUEST = "LOGGED_OUT_REQUEST"
const LOGGED_OUT_SUCCESSFUL = "LOGGED_OUT_SUCCESSFUL"
const LOGGED_OUT_FAILED = "LOGGED_OUT_FAILED"
const CHECK_IS_LOGGED_IN_REQUEST = "CHECK_IS_LOGGED_IN_REQUEST"
const IS_ALREADY_LOGGED_IN = "IS_ALREADY_LOGGED_IN"
const NO_USER_LOGGED_IN = "NO_USER_LOGGED_IN"


export {
    LOGGED_IN_REQUEST,
    LOGGED_IN_SUCCESSFUL,
    LOGGED_IN_FAILED,
    CHECK_IS_LOGGED_IN_REQUEST,
    LOGGED_OUT_SUCCESSFUL,
    LOGGED_OUT_FAILED,
    LOGGED_OUT_REQUEST,
    IS_ALREADY_LOGGED_IN,
    NO_USER_LOGGED_IN
}