const GET_AIR_DATA = "GET_AIR_DATA"
const UPDATE_AIR_DATA = "UPDATE_AIR_DATA"
const DELETE_AIR_DATA = "DELETE_AIR_DATA"
const UPDATE_AIR_DATA_STATE = "UPDATE_AIR_DATA_STATE"
const AIR_DATA_NOT_FOUND = "AIR_DATA_NOT_FOUND"





export {
    GET_AIR_DATA,
    UPDATE_AIR_DATA,
    DELETE_AIR_DATA,
    AIR_DATA_NOT_FOUND,
    UPDATE_AIR_DATA_STATE
}