const GET_AIR_DATA = "GET_AIR_DATA"
const UPDATE_AIR_DATA = "UPDATE_AIR_DATA"
const DELETE_AIR_DATA = "DELETE_AIR_DATA"
const UPDATE_AIR_DATA_STATE = "UPDATE_AIR_DATA_STATE"
const AIR_DATA_NOT_FOUND = "AIR_DATA_NOT_FOUND"
const REQUEST_FOR_UPDATE = "REQUEST_FOR_UPDATE"
const SUCCESSFULLY_UPDATE = "SUCCESSFULLY_UPDATE"
const FAILED_TO_UPDATE = "FAILED_TO_UPDATE"




export {
    GET_AIR_DATA,
    UPDATE_AIR_DATA,
    DELETE_AIR_DATA,
    AIR_DATA_NOT_FOUND,
    UPDATE_AIR_DATA_STATE,
    REQUEST_FOR_UPDATE,
    SUCCESSFULLY_UPDATE,
    FAILED_TO_UPDATE
}